sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 070911

  alioss:
    endpoint: yourendpoint
    access-key-id: yourkey
    access-key-secret: yoursecret
    bucket-name: yourbucket

  redis:
    host: localhost
    port: 6379
    password:
    database: 10